# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:   potatosalad
tagline: blog
email:   potatosaladx@gmail.com
description: >
  The Development Blog of Andrew Bennett
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://potatosalad.io" # the base hostname & protocol for your site
twitter_username: potatosaladx
twitter:
  username: potatosaladx
github_username:  potatosalad
paginate: 5
author:
  name:    Andrew Bennett
  twitter: https://twitter.com/potatosaladx
  github:  https://github.com/potatosalad

# Tags
tag_page_layout: tag_page
tag_page_dir:    tag

# Custom vars
version: 1.0.0

# Build settings
highlighter: rouge
markdown: redcarpet
gems:
  - jekyll-angular
  - jekyll-compose
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll/tagging

# Exclusions
exclude:
  - util/
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - Rakefile
  - README.md
