# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               potatosalad
tagline:             'blog'
description:         'The Development Blog of Andrew Bennett'
url:                 https://potatosalad.github.io
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              'Andrew Bennett'
  twitter:           https://twitter.com/potatosaladx
  github:            https://github.com/potatosalad

# Tags
tag_page_layout:     tag_page
tag_page_dir:        tag

# Custom vars
version:             1.0.0
